/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using OpenSubtitles.Client;
using OpenSubtitles.Model;

namespace OpenSubtitles.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFeaturesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search for features
        /// </summary>
        /// <remarks>
        /// With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </remarks>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <returns>InlineResponse2006</returns>
        InlineResponse2006 Features (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?));

        /// <summary>
        /// Search for features
        /// </summary>
        /// <remarks>
        /// With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </remarks>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <returns>ApiResponse of InlineResponse2006</returns>
        ApiResponse<InlineResponse2006> FeaturesWithHttpInfo (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Search for features
        /// </summary>
        /// <remarks>
        /// With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </remarks>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of InlineResponse2006</returns>
        System.Threading.Tasks.Task<InlineResponse2006> FeaturesAsync (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Search for features
        /// </summary>
        /// <remarks>
        /// With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </remarks>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (InlineResponse2006)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2006>> FeaturesWithHttpInfoAsync (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FeaturesApi : IFeaturesApi
    {
        private OpenSubtitles.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FeaturesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FeaturesApi(String basePath)
        {
            this.Configuration = new OpenSubtitles.Client.Configuration { BasePath = basePath };

            ExceptionFactory = OpenSubtitles.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeaturesApi"/> class
        /// </summary>
        /// <returns></returns>
        public FeaturesApi()
        {
            this.Configuration = OpenSubtitles.Client.Configuration.Default;

            ExceptionFactory = OpenSubtitles.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeaturesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FeaturesApi(OpenSubtitles.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = OpenSubtitles.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = OpenSubtitles.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OpenSubtitles.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OpenSubtitles.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Search for features With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </summary>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <returns>InlineResponse2006</returns>
        public InlineResponse2006 Features (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?))
        {
             ApiResponse<InlineResponse2006> localVarResponse = FeaturesWithHttpInfo(query, type, featureId, imdbId, tmdbId, year);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search for features With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </summary>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <returns>ApiResponse of InlineResponse2006</returns>
        public ApiResponse<InlineResponse2006> FeaturesWithHttpInfo (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?))
        {

            var localVarPath = "/features";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "example"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (query != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "query", query)); // query parameter
            if (type != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "type", type)); // query parameter
            if (featureId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "feature_id", featureId)); // query parameter
            if (imdbId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "imdb_id", imdbId)); // query parameter
            if (tmdbId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "tmdb_id", tmdbId)); // query parameter
            if (year != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "year", year)); // query parameter

            // authentication (Api-Key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Key")))
            {
                localVarHeaderParams["Api-Key"] = this.Configuration.GetApiKeyWithPrefix("Api-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Features", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2006>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse2006) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2006)));
        }

        /// <summary>
        /// Search for features With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </summary>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of InlineResponse2006</returns>
        public async System.Threading.Tasks.Task<InlineResponse2006> FeaturesAsync (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<InlineResponse2006> localVarResponse = await FeaturesWithHttpInfoAsync(query, type, featureId, imdbId, tmdbId, year, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search for features With the \&quot;query\&quot; parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  &lt;!- - theme: warning - -&gt;  &gt; ### Watch Out! &gt; &gt; If you create an autocomplete, don&#39;t set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!
        /// </summary>
        /// <exception cref="OpenSubtitles.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">quary to search (optional)</param>
        /// <param name="type">empty to list all or **movie**, **tvshow** or **episode**. (optional)</param>
        /// <param name="featureId">opensubtitles **feature_id** (optional)</param>
        /// <param name="imdbId">IMDB ID, delete leading zeroes (optional)</param>
        /// <param name="tmdbId">TheMovieDB ID - combine with type to avoid errors (optional)</param>
        /// <param name="year">Filter by year. Can only be used in combination with a query (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (InlineResponse2006)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse2006>> FeaturesWithHttpInfoAsync (string query = default(string), string type = default(string), int? featureId = default(int?), string imdbId = default(string), string tmdbId = default(string), int? year = default(int?), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/features";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "example"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (query != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "query", query)); // query parameter
            if (type != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "type", type)); // query parameter
            if (featureId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "feature_id", featureId)); // query parameter
            if (imdbId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "imdb_id", imdbId)); // query parameter
            if (tmdbId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "tmdb_id", tmdbId)); // query parameter
            if (year != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "year", year)); // query parameter

            // authentication (Api-Key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Api-Key")))
            {
                localVarHeaderParams["Api-Key"] = this.Configuration.GetApiKeyWithPrefix("Api-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Features", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2006>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (InlineResponse2006) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2006)));
        }

    }
}
