/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OpenSubtitles.Client.OpenAPIDateConverter;

namespace OpenSubtitles.Model
{
    /// <summary>
    /// FeatureTvshowAttributesSubtitlesCounts
    /// </summary>
    [DataContract]
    public partial class FeatureTvshowAttributesSubtitlesCounts :  IEquatable<FeatureTvshowAttributesSubtitlesCounts>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureTvshowAttributesSubtitlesCounts" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeatureTvshowAttributesSubtitlesCounts() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureTvshowAttributesSubtitlesCounts" /> class.
        /// </summary>
        /// <param name="pl">pl (required).</param>
        /// <param name="en">en (required).</param>
        /// <param name="ptBR">ptBR (required).</param>
        /// <param name="ro">ro (required).</param>
        /// <param name="nl">nl (required).</param>
        /// <param name="ptPT">ptPT (required).</param>
        /// <param name="es">es (required).</param>
        /// <param name="he">he (required).</param>
        /// <param name="hu">hu (required).</param>
        /// <param name="el">el (required).</param>
        /// <param name="fr">fr (required).</param>
        /// <param name="tr">tr (required).</param>
        /// <param name="cs">cs (required).</param>
        /// <param name="fi">fi (required).</param>
        /// <param name="ar">ar (required).</param>
        /// <param name="hr">hr (required).</param>
        /// <param name="sl">sl (required).</param>
        /// <param name="bg">bg (required).</param>
        /// <param name="sr">sr (required).</param>
        /// <param name="sv">sv (required).</param>
        /// <param name="de">de (required).</param>
        /// <param name="et">et (required).</param>
        /// <param name="da">da (required).</param>
        /// <param name="bs">bs (required).</param>
        /// <param name="it">it (required).</param>
        /// <param name="mk">mk (required).</param>
        /// <param name="ru">ru (required).</param>
        /// <param name="no">no (required).</param>
        /// <param name="th">th (required).</param>
        /// <param name="vi">vi (required).</param>
        /// <param name="ja">ja (required).</param>
        /// <param name="fa">fa (required).</param>
        /// <param name="zhCN">zhCN (required).</param>
        /// <param name="ca">ca (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="sk">sk (required).</param>
        /// <param name="ko">ko (required).</param>
        /// <param name="zhTW">zhTW (required).</param>
        public FeatureTvshowAttributesSubtitlesCounts(decimal pl = default(decimal), decimal en = default(decimal), decimal ptBR = default(decimal), decimal ro = default(decimal), decimal nl = default(decimal), decimal ptPT = default(decimal), decimal es = default(decimal), decimal he = default(decimal), decimal hu = default(decimal), decimal el = default(decimal), decimal fr = default(decimal), decimal tr = default(decimal), decimal cs = default(decimal), decimal fi = default(decimal), decimal ar = default(decimal), decimal hr = default(decimal), decimal sl = default(decimal), decimal bg = default(decimal), decimal sr = default(decimal), decimal sv = default(decimal), decimal de = default(decimal), decimal et = default(decimal), decimal da = default(decimal), decimal bs = default(decimal), decimal it = default(decimal), decimal mk = default(decimal), decimal ru = default(decimal), decimal no = default(decimal), decimal th = default(decimal), decimal vi = default(decimal), decimal ja = default(decimal), decimal fa = default(decimal), decimal zhCN = default(decimal), decimal ca = default(decimal), decimal id = default(decimal), decimal sk = default(decimal), decimal ko = default(decimal), decimal zhTW = default(decimal))
        {
            // to ensure "pl" is required (not null)
            if (pl == null)
            {
                throw new InvalidDataException("pl is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Pl = pl;
            }

            // to ensure "en" is required (not null)
            if (en == null)
            {
                throw new InvalidDataException("en is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.En = en;
            }

            // to ensure "ptBR" is required (not null)
            if (ptBR == null)
            {
                throw new InvalidDataException("ptBR is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.PtBR = ptBR;
            }

            // to ensure "ro" is required (not null)
            if (ro == null)
            {
                throw new InvalidDataException("ro is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Ro = ro;
            }

            // to ensure "nl" is required (not null)
            if (nl == null)
            {
                throw new InvalidDataException("nl is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Nl = nl;
            }

            // to ensure "ptPT" is required (not null)
            if (ptPT == null)
            {
                throw new InvalidDataException("ptPT is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.PtPT = ptPT;
            }

            // to ensure "es" is required (not null)
            if (es == null)
            {
                throw new InvalidDataException("es is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Es = es;
            }

            // to ensure "he" is required (not null)
            if (he == null)
            {
                throw new InvalidDataException("he is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.He = he;
            }

            // to ensure "hu" is required (not null)
            if (hu == null)
            {
                throw new InvalidDataException("hu is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Hu = hu;
            }

            // to ensure "el" is required (not null)
            if (el == null)
            {
                throw new InvalidDataException("el is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.El = el;
            }

            // to ensure "fr" is required (not null)
            if (fr == null)
            {
                throw new InvalidDataException("fr is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Fr = fr;
            }

            // to ensure "tr" is required (not null)
            if (tr == null)
            {
                throw new InvalidDataException("tr is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Tr = tr;
            }

            // to ensure "cs" is required (not null)
            if (cs == null)
            {
                throw new InvalidDataException("cs is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Cs = cs;
            }

            // to ensure "fi" is required (not null)
            if (fi == null)
            {
                throw new InvalidDataException("fi is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Fi = fi;
            }

            // to ensure "ar" is required (not null)
            if (ar == null)
            {
                throw new InvalidDataException("ar is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Ar = ar;
            }

            // to ensure "hr" is required (not null)
            if (hr == null)
            {
                throw new InvalidDataException("hr is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Hr = hr;
            }

            // to ensure "sl" is required (not null)
            if (sl == null)
            {
                throw new InvalidDataException("sl is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Sl = sl;
            }

            // to ensure "bg" is required (not null)
            if (bg == null)
            {
                throw new InvalidDataException("bg is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Bg = bg;
            }

            // to ensure "sr" is required (not null)
            if (sr == null)
            {
                throw new InvalidDataException("sr is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Sr = sr;
            }

            // to ensure "sv" is required (not null)
            if (sv == null)
            {
                throw new InvalidDataException("sv is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Sv = sv;
            }

            // to ensure "de" is required (not null)
            if (de == null)
            {
                throw new InvalidDataException("de is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.De = de;
            }

            // to ensure "et" is required (not null)
            if (et == null)
            {
                throw new InvalidDataException("et is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Et = et;
            }

            // to ensure "da" is required (not null)
            if (da == null)
            {
                throw new InvalidDataException("da is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Da = da;
            }

            // to ensure "bs" is required (not null)
            if (bs == null)
            {
                throw new InvalidDataException("bs is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Bs = bs;
            }

            // to ensure "it" is required (not null)
            if (it == null)
            {
                throw new InvalidDataException("it is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.It = it;
            }

            // to ensure "mk" is required (not null)
            if (mk == null)
            {
                throw new InvalidDataException("mk is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Mk = mk;
            }

            // to ensure "ru" is required (not null)
            if (ru == null)
            {
                throw new InvalidDataException("ru is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Ru = ru;
            }

            // to ensure "no" is required (not null)
            if (no == null)
            {
                throw new InvalidDataException("no is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.No = no;
            }

            // to ensure "th" is required (not null)
            if (th == null)
            {
                throw new InvalidDataException("th is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Th = th;
            }

            // to ensure "vi" is required (not null)
            if (vi == null)
            {
                throw new InvalidDataException("vi is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Vi = vi;
            }

            // to ensure "ja" is required (not null)
            if (ja == null)
            {
                throw new InvalidDataException("ja is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Ja = ja;
            }

            // to ensure "fa" is required (not null)
            if (fa == null)
            {
                throw new InvalidDataException("fa is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Fa = fa;
            }

            // to ensure "zhCN" is required (not null)
            if (zhCN == null)
            {
                throw new InvalidDataException("zhCN is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.ZhCN = zhCN;
            }

            // to ensure "ca" is required (not null)
            if (ca == null)
            {
                throw new InvalidDataException("ca is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Ca = ca;
            }

            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Id = id;
            }

            // to ensure "sk" is required (not null)
            if (sk == null)
            {
                throw new InvalidDataException("sk is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Sk = sk;
            }

            // to ensure "ko" is required (not null)
            if (ko == null)
            {
                throw new InvalidDataException("ko is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.Ko = ko;
            }

            // to ensure "zhTW" is required (not null)
            if (zhTW == null)
            {
                throw new InvalidDataException("zhTW is a required property for FeatureTvshowAttributesSubtitlesCounts and cannot be null");
            }
            else
            {
                this.ZhTW = zhTW;
            }

        }

        /// <summary>
        /// Gets or Sets Pl
        /// </summary>
        [DataMember(Name="pl", EmitDefaultValue=true)]
        public decimal Pl { get; set; }

        /// <summary>
        /// Gets or Sets En
        /// </summary>
        [DataMember(Name="en", EmitDefaultValue=true)]
        public decimal En { get; set; }

        /// <summary>
        /// Gets or Sets PtBR
        /// </summary>
        [DataMember(Name="pt-BR", EmitDefaultValue=true)]
        public decimal PtBR { get; set; }

        /// <summary>
        /// Gets or Sets Ro
        /// </summary>
        [DataMember(Name="ro", EmitDefaultValue=true)]
        public decimal Ro { get; set; }

        /// <summary>
        /// Gets or Sets Nl
        /// </summary>
        [DataMember(Name="nl", EmitDefaultValue=true)]
        public decimal Nl { get; set; }

        /// <summary>
        /// Gets or Sets PtPT
        /// </summary>
        [DataMember(Name="pt-PT", EmitDefaultValue=true)]
        public decimal PtPT { get; set; }

        /// <summary>
        /// Gets or Sets Es
        /// </summary>
        [DataMember(Name="es", EmitDefaultValue=true)]
        public decimal Es { get; set; }

        /// <summary>
        /// Gets or Sets He
        /// </summary>
        [DataMember(Name="he", EmitDefaultValue=true)]
        public decimal He { get; set; }

        /// <summary>
        /// Gets or Sets Hu
        /// </summary>
        [DataMember(Name="hu", EmitDefaultValue=true)]
        public decimal Hu { get; set; }

        /// <summary>
        /// Gets or Sets El
        /// </summary>
        [DataMember(Name="el", EmitDefaultValue=true)]
        public decimal El { get; set; }

        /// <summary>
        /// Gets or Sets Fr
        /// </summary>
        [DataMember(Name="fr", EmitDefaultValue=true)]
        public decimal Fr { get; set; }

        /// <summary>
        /// Gets or Sets Tr
        /// </summary>
        [DataMember(Name="tr", EmitDefaultValue=true)]
        public decimal Tr { get; set; }

        /// <summary>
        /// Gets or Sets Cs
        /// </summary>
        [DataMember(Name="cs", EmitDefaultValue=true)]
        public decimal Cs { get; set; }

        /// <summary>
        /// Gets or Sets Fi
        /// </summary>
        [DataMember(Name="fi", EmitDefaultValue=true)]
        public decimal Fi { get; set; }

        /// <summary>
        /// Gets or Sets Ar
        /// </summary>
        [DataMember(Name="ar", EmitDefaultValue=true)]
        public decimal Ar { get; set; }

        /// <summary>
        /// Gets or Sets Hr
        /// </summary>
        [DataMember(Name="hr", EmitDefaultValue=true)]
        public decimal Hr { get; set; }

        /// <summary>
        /// Gets or Sets Sl
        /// </summary>
        [DataMember(Name="sl", EmitDefaultValue=true)]
        public decimal Sl { get; set; }

        /// <summary>
        /// Gets or Sets Bg
        /// </summary>
        [DataMember(Name="bg", EmitDefaultValue=true)]
        public decimal Bg { get; set; }

        /// <summary>
        /// Gets or Sets Sr
        /// </summary>
        [DataMember(Name="sr", EmitDefaultValue=true)]
        public decimal Sr { get; set; }

        /// <summary>
        /// Gets or Sets Sv
        /// </summary>
        [DataMember(Name="sv", EmitDefaultValue=true)]
        public decimal Sv { get; set; }

        /// <summary>
        /// Gets or Sets De
        /// </summary>
        [DataMember(Name="de", EmitDefaultValue=true)]
        public decimal De { get; set; }

        /// <summary>
        /// Gets or Sets Et
        /// </summary>
        [DataMember(Name="et", EmitDefaultValue=true)]
        public decimal Et { get; set; }

        /// <summary>
        /// Gets or Sets Da
        /// </summary>
        [DataMember(Name="da", EmitDefaultValue=true)]
        public decimal Da { get; set; }

        /// <summary>
        /// Gets or Sets Bs
        /// </summary>
        [DataMember(Name="bs", EmitDefaultValue=true)]
        public decimal Bs { get; set; }

        /// <summary>
        /// Gets or Sets It
        /// </summary>
        [DataMember(Name="it", EmitDefaultValue=true)]
        public decimal It { get; set; }

        /// <summary>
        /// Gets or Sets Mk
        /// </summary>
        [DataMember(Name="mk", EmitDefaultValue=true)]
        public decimal Mk { get; set; }

        /// <summary>
        /// Gets or Sets Ru
        /// </summary>
        [DataMember(Name="ru", EmitDefaultValue=true)]
        public decimal Ru { get; set; }

        /// <summary>
        /// Gets or Sets No
        /// </summary>
        [DataMember(Name="no", EmitDefaultValue=true)]
        public decimal No { get; set; }

        /// <summary>
        /// Gets or Sets Th
        /// </summary>
        [DataMember(Name="th", EmitDefaultValue=true)]
        public decimal Th { get; set; }

        /// <summary>
        /// Gets or Sets Vi
        /// </summary>
        [DataMember(Name="vi", EmitDefaultValue=true)]
        public decimal Vi { get; set; }

        /// <summary>
        /// Gets or Sets Ja
        /// </summary>
        [DataMember(Name="ja", EmitDefaultValue=true)]
        public decimal Ja { get; set; }

        /// <summary>
        /// Gets or Sets Fa
        /// </summary>
        [DataMember(Name="fa", EmitDefaultValue=true)]
        public decimal Fa { get; set; }

        /// <summary>
        /// Gets or Sets ZhCN
        /// </summary>
        [DataMember(Name="zh-CN", EmitDefaultValue=true)]
        public decimal ZhCN { get; set; }

        /// <summary>
        /// Gets or Sets Ca
        /// </summary>
        [DataMember(Name="ca", EmitDefaultValue=true)]
        public decimal Ca { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Gets or Sets Sk
        /// </summary>
        [DataMember(Name="sk", EmitDefaultValue=true)]
        public decimal Sk { get; set; }

        /// <summary>
        /// Gets or Sets Ko
        /// </summary>
        [DataMember(Name="ko", EmitDefaultValue=true)]
        public decimal Ko { get; set; }

        /// <summary>
        /// Gets or Sets ZhTW
        /// </summary>
        [DataMember(Name="zh-TW", EmitDefaultValue=true)]
        public decimal ZhTW { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FeatureTvshowAttributesSubtitlesCounts {\n");
            sb.Append("  Pl: ").Append(Pl).Append("\n");
            sb.Append("  En: ").Append(En).Append("\n");
            sb.Append("  PtBR: ").Append(PtBR).Append("\n");
            sb.Append("  Ro: ").Append(Ro).Append("\n");
            sb.Append("  Nl: ").Append(Nl).Append("\n");
            sb.Append("  PtPT: ").Append(PtPT).Append("\n");
            sb.Append("  Es: ").Append(Es).Append("\n");
            sb.Append("  He: ").Append(He).Append("\n");
            sb.Append("  Hu: ").Append(Hu).Append("\n");
            sb.Append("  El: ").Append(El).Append("\n");
            sb.Append("  Fr: ").Append(Fr).Append("\n");
            sb.Append("  Tr: ").Append(Tr).Append("\n");
            sb.Append("  Cs: ").Append(Cs).Append("\n");
            sb.Append("  Fi: ").Append(Fi).Append("\n");
            sb.Append("  Ar: ").Append(Ar).Append("\n");
            sb.Append("  Hr: ").Append(Hr).Append("\n");
            sb.Append("  Sl: ").Append(Sl).Append("\n");
            sb.Append("  Bg: ").Append(Bg).Append("\n");
            sb.Append("  Sr: ").Append(Sr).Append("\n");
            sb.Append("  Sv: ").Append(Sv).Append("\n");
            sb.Append("  De: ").Append(De).Append("\n");
            sb.Append("  Et: ").Append(Et).Append("\n");
            sb.Append("  Da: ").Append(Da).Append("\n");
            sb.Append("  Bs: ").Append(Bs).Append("\n");
            sb.Append("  It: ").Append(It).Append("\n");
            sb.Append("  Mk: ").Append(Mk).Append("\n");
            sb.Append("  Ru: ").Append(Ru).Append("\n");
            sb.Append("  No: ").Append(No).Append("\n");
            sb.Append("  Th: ").Append(Th).Append("\n");
            sb.Append("  Vi: ").Append(Vi).Append("\n");
            sb.Append("  Ja: ").Append(Ja).Append("\n");
            sb.Append("  Fa: ").Append(Fa).Append("\n");
            sb.Append("  ZhCN: ").Append(ZhCN).Append("\n");
            sb.Append("  Ca: ").Append(Ca).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Sk: ").Append(Sk).Append("\n");
            sb.Append("  Ko: ").Append(Ko).Append("\n");
            sb.Append("  ZhTW: ").Append(ZhTW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FeatureTvshowAttributesSubtitlesCounts);
        }

        /// <summary>
        /// Returns true if FeatureTvshowAttributesSubtitlesCounts instances are equal
        /// </summary>
        /// <param name="input">Instance of FeatureTvshowAttributesSubtitlesCounts to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FeatureTvshowAttributesSubtitlesCounts input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pl == input.Pl ||
                    (this.Pl != null &&
                    this.Pl.Equals(input.Pl))
                ) && 
                (
                    this.En == input.En ||
                    (this.En != null &&
                    this.En.Equals(input.En))
                ) && 
                (
                    this.PtBR == input.PtBR ||
                    (this.PtBR != null &&
                    this.PtBR.Equals(input.PtBR))
                ) && 
                (
                    this.Ro == input.Ro ||
                    (this.Ro != null &&
                    this.Ro.Equals(input.Ro))
                ) && 
                (
                    this.Nl == input.Nl ||
                    (this.Nl != null &&
                    this.Nl.Equals(input.Nl))
                ) && 
                (
                    this.PtPT == input.PtPT ||
                    (this.PtPT != null &&
                    this.PtPT.Equals(input.PtPT))
                ) && 
                (
                    this.Es == input.Es ||
                    (this.Es != null &&
                    this.Es.Equals(input.Es))
                ) && 
                (
                    this.He == input.He ||
                    (this.He != null &&
                    this.He.Equals(input.He))
                ) && 
                (
                    this.Hu == input.Hu ||
                    (this.Hu != null &&
                    this.Hu.Equals(input.Hu))
                ) && 
                (
                    this.El == input.El ||
                    (this.El != null &&
                    this.El.Equals(input.El))
                ) && 
                (
                    this.Fr == input.Fr ||
                    (this.Fr != null &&
                    this.Fr.Equals(input.Fr))
                ) && 
                (
                    this.Tr == input.Tr ||
                    (this.Tr != null &&
                    this.Tr.Equals(input.Tr))
                ) && 
                (
                    this.Cs == input.Cs ||
                    (this.Cs != null &&
                    this.Cs.Equals(input.Cs))
                ) && 
                (
                    this.Fi == input.Fi ||
                    (this.Fi != null &&
                    this.Fi.Equals(input.Fi))
                ) && 
                (
                    this.Ar == input.Ar ||
                    (this.Ar != null &&
                    this.Ar.Equals(input.Ar))
                ) && 
                (
                    this.Hr == input.Hr ||
                    (this.Hr != null &&
                    this.Hr.Equals(input.Hr))
                ) && 
                (
                    this.Sl == input.Sl ||
                    (this.Sl != null &&
                    this.Sl.Equals(input.Sl))
                ) && 
                (
                    this.Bg == input.Bg ||
                    (this.Bg != null &&
                    this.Bg.Equals(input.Bg))
                ) && 
                (
                    this.Sr == input.Sr ||
                    (this.Sr != null &&
                    this.Sr.Equals(input.Sr))
                ) && 
                (
                    this.Sv == input.Sv ||
                    (this.Sv != null &&
                    this.Sv.Equals(input.Sv))
                ) && 
                (
                    this.De == input.De ||
                    (this.De != null &&
                    this.De.Equals(input.De))
                ) && 
                (
                    this.Et == input.Et ||
                    (this.Et != null &&
                    this.Et.Equals(input.Et))
                ) && 
                (
                    this.Da == input.Da ||
                    (this.Da != null &&
                    this.Da.Equals(input.Da))
                ) && 
                (
                    this.Bs == input.Bs ||
                    (this.Bs != null &&
                    this.Bs.Equals(input.Bs))
                ) && 
                (
                    this.It == input.It ||
                    (this.It != null &&
                    this.It.Equals(input.It))
                ) && 
                (
                    this.Mk == input.Mk ||
                    (this.Mk != null &&
                    this.Mk.Equals(input.Mk))
                ) && 
                (
                    this.Ru == input.Ru ||
                    (this.Ru != null &&
                    this.Ru.Equals(input.Ru))
                ) && 
                (
                    this.No == input.No ||
                    (this.No != null &&
                    this.No.Equals(input.No))
                ) && 
                (
                    this.Th == input.Th ||
                    (this.Th != null &&
                    this.Th.Equals(input.Th))
                ) && 
                (
                    this.Vi == input.Vi ||
                    (this.Vi != null &&
                    this.Vi.Equals(input.Vi))
                ) && 
                (
                    this.Ja == input.Ja ||
                    (this.Ja != null &&
                    this.Ja.Equals(input.Ja))
                ) && 
                (
                    this.Fa == input.Fa ||
                    (this.Fa != null &&
                    this.Fa.Equals(input.Fa))
                ) && 
                (
                    this.ZhCN == input.ZhCN ||
                    (this.ZhCN != null &&
                    this.ZhCN.Equals(input.ZhCN))
                ) && 
                (
                    this.Ca == input.Ca ||
                    (this.Ca != null &&
                    this.Ca.Equals(input.Ca))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Sk == input.Sk ||
                    (this.Sk != null &&
                    this.Sk.Equals(input.Sk))
                ) && 
                (
                    this.Ko == input.Ko ||
                    (this.Ko != null &&
                    this.Ko.Equals(input.Ko))
                ) && 
                (
                    this.ZhTW == input.ZhTW ||
                    (this.ZhTW != null &&
                    this.ZhTW.Equals(input.ZhTW))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pl != null)
                    hashCode = hashCode * 59 + this.Pl.GetHashCode();
                if (this.En != null)
                    hashCode = hashCode * 59 + this.En.GetHashCode();
                if (this.PtBR != null)
                    hashCode = hashCode * 59 + this.PtBR.GetHashCode();
                if (this.Ro != null)
                    hashCode = hashCode * 59 + this.Ro.GetHashCode();
                if (this.Nl != null)
                    hashCode = hashCode * 59 + this.Nl.GetHashCode();
                if (this.PtPT != null)
                    hashCode = hashCode * 59 + this.PtPT.GetHashCode();
                if (this.Es != null)
                    hashCode = hashCode * 59 + this.Es.GetHashCode();
                if (this.He != null)
                    hashCode = hashCode * 59 + this.He.GetHashCode();
                if (this.Hu != null)
                    hashCode = hashCode * 59 + this.Hu.GetHashCode();
                if (this.El != null)
                    hashCode = hashCode * 59 + this.El.GetHashCode();
                if (this.Fr != null)
                    hashCode = hashCode * 59 + this.Fr.GetHashCode();
                if (this.Tr != null)
                    hashCode = hashCode * 59 + this.Tr.GetHashCode();
                if (this.Cs != null)
                    hashCode = hashCode * 59 + this.Cs.GetHashCode();
                if (this.Fi != null)
                    hashCode = hashCode * 59 + this.Fi.GetHashCode();
                if (this.Ar != null)
                    hashCode = hashCode * 59 + this.Ar.GetHashCode();
                if (this.Hr != null)
                    hashCode = hashCode * 59 + this.Hr.GetHashCode();
                if (this.Sl != null)
                    hashCode = hashCode * 59 + this.Sl.GetHashCode();
                if (this.Bg != null)
                    hashCode = hashCode * 59 + this.Bg.GetHashCode();
                if (this.Sr != null)
                    hashCode = hashCode * 59 + this.Sr.GetHashCode();
                if (this.Sv != null)
                    hashCode = hashCode * 59 + this.Sv.GetHashCode();
                if (this.De != null)
                    hashCode = hashCode * 59 + this.De.GetHashCode();
                if (this.Et != null)
                    hashCode = hashCode * 59 + this.Et.GetHashCode();
                if (this.Da != null)
                    hashCode = hashCode * 59 + this.Da.GetHashCode();
                if (this.Bs != null)
                    hashCode = hashCode * 59 + this.Bs.GetHashCode();
                if (this.It != null)
                    hashCode = hashCode * 59 + this.It.GetHashCode();
                if (this.Mk != null)
                    hashCode = hashCode * 59 + this.Mk.GetHashCode();
                if (this.Ru != null)
                    hashCode = hashCode * 59 + this.Ru.GetHashCode();
                if (this.No != null)
                    hashCode = hashCode * 59 + this.No.GetHashCode();
                if (this.Th != null)
                    hashCode = hashCode * 59 + this.Th.GetHashCode();
                if (this.Vi != null)
                    hashCode = hashCode * 59 + this.Vi.GetHashCode();
                if (this.Ja != null)
                    hashCode = hashCode * 59 + this.Ja.GetHashCode();
                if (this.Fa != null)
                    hashCode = hashCode * 59 + this.Fa.GetHashCode();
                if (this.ZhCN != null)
                    hashCode = hashCode * 59 + this.ZhCN.GetHashCode();
                if (this.Ca != null)
                    hashCode = hashCode * 59 + this.Ca.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Sk != null)
                    hashCode = hashCode * 59 + this.Sk.GetHashCode();
                if (this.Ko != null)
                    hashCode = hashCode * 59 + this.Ko.GetHashCode();
                if (this.ZhTW != null)
                    hashCode = hashCode * 59 + this.ZhTW.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
