/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing FeatureMovieAttributesSubtitlesCounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeatureMovieAttributesSubtitlesCountsTests
    {
        // TODO uncomment below to declare an instance variable for FeatureMovieAttributesSubtitlesCounts
        //private FeatureMovieAttributesSubtitlesCounts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureMovieAttributesSubtitlesCounts
            //instance = new FeatureMovieAttributesSubtitlesCounts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureMovieAttributesSubtitlesCounts
        /// </summary>
        [Test]
        public void FeatureMovieAttributesSubtitlesCountsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FeatureMovieAttributesSubtitlesCounts
            //Assert.IsInstanceOf(typeof(FeatureMovieAttributesSubtitlesCounts), instance);
        }


        /// <summary>
        /// Test the property 'En'
        /// </summary>
        [Test]
        public void EnTest()
        {
            // TODO unit test for the property 'En'
        }
        /// <summary>
        /// Test the property 'PtPT'
        /// </summary>
        [Test]
        public void PtPTTest()
        {
            // TODO unit test for the property 'PtPT'
        }
        /// <summary>
        /// Test the property 'Fi'
        /// </summary>
        [Test]
        public void FiTest()
        {
            // TODO unit test for the property 'Fi'
        }
        /// <summary>
        /// Test the property 'PtBR'
        /// </summary>
        [Test]
        public void PtBRTest()
        {
            // TODO unit test for the property 'PtBR'
        }
        /// <summary>
        /// Test the property 'Es'
        /// </summary>
        [Test]
        public void EsTest()
        {
            // TODO unit test for the property 'Es'
        }
        /// <summary>
        /// Test the property 'Ar'
        /// </summary>
        [Test]
        public void ArTest()
        {
            // TODO unit test for the property 'Ar'
        }
        /// <summary>
        /// Test the property 'Pl'
        /// </summary>
        [Test]
        public void PlTest()
        {
            // TODO unit test for the property 'Pl'
        }
        /// <summary>
        /// Test the property 'Sr'
        /// </summary>
        [Test]
        public void SrTest()
        {
            // TODO unit test for the property 'Sr'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Ro'
        /// </summary>
        [Test]
        public void RoTest()
        {
            // TODO unit test for the property 'Ro'
        }
        /// <summary>
        /// Test the property 'ZhCN'
        /// </summary>
        [Test]
        public void ZhCNTest()
        {
            // TODO unit test for the property 'ZhCN'
        }
        /// <summary>
        /// Test the property 'Nl'
        /// </summary>
        [Test]
        public void NlTest()
        {
            // TODO unit test for the property 'Nl'
        }
        /// <summary>
        /// Test the property 'El'
        /// </summary>
        [Test]
        public void ElTest()
        {
            // TODO unit test for the property 'El'
        }
        /// <summary>
        /// Test the property 'Hu'
        /// </summary>
        [Test]
        public void HuTest()
        {
            // TODO unit test for the property 'Hu'
        }
        /// <summary>
        /// Test the property 'Fr'
        /// </summary>
        [Test]
        public void FrTest()
        {
            // TODO unit test for the property 'Fr'
        }
        /// <summary>
        /// Test the property 'Sl'
        /// </summary>
        [Test]
        public void SlTest()
        {
            // TODO unit test for the property 'Sl'
        }
        /// <summary>
        /// Test the property 'Tr'
        /// </summary>
        [Test]
        public void TrTest()
        {
            // TODO unit test for the property 'Tr'
        }
        /// <summary>
        /// Test the property 'Et'
        /// </summary>
        [Test]
        public void EtTest()
        {
            // TODO unit test for the property 'Et'
        }
        /// <summary>
        /// Test the property 'Bg'
        /// </summary>
        [Test]
        public void BgTest()
        {
            // TODO unit test for the property 'Bg'
        }
        /// <summary>
        /// Test the property 'Cs'
        /// </summary>
        [Test]
        public void CsTest()
        {
            // TODO unit test for the property 'Cs'
        }
        /// <summary>
        /// Test the property 'De'
        /// </summary>
        [Test]
        public void DeTest()
        {
            // TODO unit test for the property 'De'
        }
        /// <summary>
        /// Test the property 'He'
        /// </summary>
        [Test]
        public void HeTest()
        {
            // TODO unit test for the property 'He'
        }
        /// <summary>
        /// Test the property 'It'
        /// </summary>
        [Test]
        public void ItTest()
        {
            // TODO unit test for the property 'It'
        }
        /// <summary>
        /// Test the property 'Vi'
        /// </summary>
        [Test]
        public void ViTest()
        {
            // TODO unit test for the property 'Vi'
        }
        /// <summary>
        /// Test the property 'Hr'
        /// </summary>
        [Test]
        public void HrTest()
        {
            // TODO unit test for the property 'Hr'
        }
        /// <summary>
        /// Test the property 'Ko'
        /// </summary>
        [Test]
        public void KoTest()
        {
            // TODO unit test for the property 'Ko'
        }
        /// <summary>
        /// Test the property 'No'
        /// </summary>
        [Test]
        public void NoTest()
        {
            // TODO unit test for the property 'No'
        }
        /// <summary>
        /// Test the property 'Sv'
        /// </summary>
        [Test]
        public void SvTest()
        {
            // TODO unit test for the property 'Sv'
        }
        /// <summary>
        /// Test the property 'Ta'
        /// </summary>
        [Test]
        public void TaTest()
        {
            // TODO unit test for the property 'Ta'
        }
        /// <summary>
        /// Test the property 'Eu'
        /// </summary>
        [Test]
        public void EuTest()
        {
            // TODO unit test for the property 'Eu'
        }
        /// <summary>
        /// Test the property 'Da'
        /// </summary>
        [Test]
        public void DaTest()
        {
            // TODO unit test for the property 'Da'
        }
        /// <summary>
        /// Test the property 'Fa'
        /// </summary>
        [Test]
        public void FaTest()
        {
            // TODO unit test for the property 'Fa'
        }
        /// <summary>
        /// Test the property 'Sk'
        /// </summary>
        [Test]
        public void SkTest()
        {
            // TODO unit test for the property 'Sk'
        }
        /// <summary>
        /// Test the property 'Uk'
        /// </summary>
        [Test]
        public void UkTest()
        {
            // TODO unit test for the property 'Uk'
        }
        /// <summary>
        /// Test the property 'ZhTW'
        /// </summary>
        [Test]
        public void ZhTWTest()
        {
            // TODO unit test for the property 'ZhTW'
        }
        /// <summary>
        /// Test the property 'Bn'
        /// </summary>
        [Test]
        public void BnTest()
        {
            // TODO unit test for the property 'Bn'
        }
        /// <summary>
        /// Test the property 'Ka'
        /// </summary>
        [Test]
        public void KaTest()
        {
            // TODO unit test for the property 'Ka'
        }
        /// <summary>
        /// Test the property 'Ja'
        /// </summary>
        [Test]
        public void JaTest()
        {
            // TODO unit test for the property 'Ja'
        }
        /// <summary>
        /// Test the property 'Lt'
        /// </summary>
        [Test]
        public void LtTest()
        {
            // TODO unit test for the property 'Lt'
        }
        /// <summary>
        /// Test the property 'Mk'
        /// </summary>
        [Test]
        public void MkTest()
        {
            // TODO unit test for the property 'Mk'
        }
        /// <summary>
        /// Test the property 'Ml'
        /// </summary>
        [Test]
        public void MlTest()
        {
            // TODO unit test for the property 'Ml'
        }
        /// <summary>
        /// Test the property 'Ms'
        /// </summary>
        [Test]
        public void MsTest()
        {
            // TODO unit test for the property 'Ms'
        }
        /// <summary>
        /// Test the property 'Ru'
        /// </summary>
        [Test]
        public void RuTest()
        {
            // TODO unit test for the property 'Ru'
        }
        /// <summary>
        /// Test the property 'Ze'
        /// </summary>
        [Test]
        public void ZeTest()
        {
            // TODO unit test for the property 'Ze'
        }

    }

}
