/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing FeatureTvshowAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeatureTvshowAttributesTests
    {
        // TODO uncomment below to declare an instance variable for FeatureTvshowAttributes
        //private FeatureTvshowAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureTvshowAttributes
            //instance = new FeatureTvshowAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureTvshowAttributes
        /// </summary>
        [Test]
        public void FeatureTvshowAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FeatureTvshowAttributes
            //Assert.IsInstanceOf(typeof(FeatureTvshowAttributes), instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'OriginalTitle'
        /// </summary>
        [Test]
        public void OriginalTitleTest()
        {
            // TODO unit test for the property 'OriginalTitle'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'ImdbId'
        /// </summary>
        [Test]
        public void ImdbIdTest()
        {
            // TODO unit test for the property 'ImdbId'
        }
        /// <summary>
        /// Test the property 'TmdbId'
        /// </summary>
        [Test]
        public void TmdbIdTest()
        {
            // TODO unit test for the property 'TmdbId'
        }
        /// <summary>
        /// Test the property 'TitleAka'
        /// </summary>
        [Test]
        public void TitleAkaTest()
        {
            // TODO unit test for the property 'TitleAka'
        }
        /// <summary>
        /// Test the property 'FeatureId'
        /// </summary>
        [Test]
        public void FeatureIdTest()
        {
            // TODO unit test for the property 'FeatureId'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'ImgUrl'
        /// </summary>
        [Test]
        public void ImgUrlTest()
        {
            // TODO unit test for the property 'ImgUrl'
        }
        /// <summary>
        /// Test the property 'SubtitlesCounts'
        /// </summary>
        [Test]
        public void SubtitlesCountsTest()
        {
            // TODO unit test for the property 'SubtitlesCounts'
        }
        /// <summary>
        /// Test the property 'SubtitlesCount'
        /// </summary>
        [Test]
        public void SubtitlesCountTest()
        {
            // TODO unit test for the property 'SubtitlesCount'
        }
        /// <summary>
        /// Test the property 'Seasons'
        /// </summary>
        [Test]
        public void SeasonsTest()
        {
            // TODO unit test for the property 'Seasons'
        }

    }

}
