/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing FeatureTvshowAttributesEpisodes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeatureTvshowAttributesEpisodesTests
    {
        // TODO uncomment below to declare an instance variable for FeatureTvshowAttributesEpisodes
        //private FeatureTvshowAttributesEpisodes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureTvshowAttributesEpisodes
            //instance = new FeatureTvshowAttributesEpisodes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureTvshowAttributesEpisodes
        /// </summary>
        [Test]
        public void FeatureTvshowAttributesEpisodesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FeatureTvshowAttributesEpisodes
            //Assert.IsInstanceOf(typeof(FeatureTvshowAttributesEpisodes), instance);
        }


        /// <summary>
        /// Test the property 'EpisodeNumber'
        /// </summary>
        [Test]
        public void EpisodeNumberTest()
        {
            // TODO unit test for the property 'EpisodeNumber'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'FeatureId'
        /// </summary>
        [Test]
        public void FeatureIdTest()
        {
            // TODO unit test for the property 'FeatureId'
        }
        /// <summary>
        /// Test the property 'FeatureImdbId'
        /// </summary>
        [Test]
        public void FeatureImdbIdTest()
        {
            // TODO unit test for the property 'FeatureImdbId'
        }

    }

}
