/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing FeatureEpisodeAttributesSubtitlesCounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeatureEpisodeAttributesSubtitlesCountsTests
    {
        // TODO uncomment below to declare an instance variable for FeatureEpisodeAttributesSubtitlesCounts
        //private FeatureEpisodeAttributesSubtitlesCounts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureEpisodeAttributesSubtitlesCounts
            //instance = new FeatureEpisodeAttributesSubtitlesCounts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureEpisodeAttributesSubtitlesCounts
        /// </summary>
        [Test]
        public void FeatureEpisodeAttributesSubtitlesCountsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FeatureEpisodeAttributesSubtitlesCounts
            //Assert.IsInstanceOf(typeof(FeatureEpisodeAttributesSubtitlesCounts), instance);
        }


        /// <summary>
        /// Test the property 'Pl'
        /// </summary>
        [Test]
        public void PlTest()
        {
            // TODO unit test for the property 'Pl'
        }
        /// <summary>
        /// Test the property 'En'
        /// </summary>
        [Test]
        public void EnTest()
        {
            // TODO unit test for the property 'En'
        }
        /// <summary>
        /// Test the property 'PtBR'
        /// </summary>
        [Test]
        public void PtBRTest()
        {
            // TODO unit test for the property 'PtBR'
        }
        /// <summary>
        /// Test the property 'Es'
        /// </summary>
        [Test]
        public void EsTest()
        {
            // TODO unit test for the property 'Es'
        }
        /// <summary>
        /// Test the property 'Ro'
        /// </summary>
        [Test]
        public void RoTest()
        {
            // TODO unit test for the property 'Ro'
        }
        /// <summary>
        /// Test the property 'Nl'
        /// </summary>
        [Test]
        public void NlTest()
        {
            // TODO unit test for the property 'Nl'
        }
        /// <summary>
        /// Test the property 'Tr'
        /// </summary>
        [Test]
        public void TrTest()
        {
            // TODO unit test for the property 'Tr'
        }
        /// <summary>
        /// Test the property 'He'
        /// </summary>
        [Test]
        public void HeTest()
        {
            // TODO unit test for the property 'He'
        }
        /// <summary>
        /// Test the property 'PtPT'
        /// </summary>
        [Test]
        public void PtPTTest()
        {
            // TODO unit test for the property 'PtPT'
        }
        /// <summary>
        /// Test the property 'Cs'
        /// </summary>
        [Test]
        public void CsTest()
        {
            // TODO unit test for the property 'Cs'
        }
        /// <summary>
        /// Test the property 'Fi'
        /// </summary>
        [Test]
        public void FiTest()
        {
            // TODO unit test for the property 'Fi'
        }
        /// <summary>
        /// Test the property 'Hu'
        /// </summary>
        [Test]
        public void HuTest()
        {
            // TODO unit test for the property 'Hu'
        }
        /// <summary>
        /// Test the property 'Ar'
        /// </summary>
        [Test]
        public void ArTest()
        {
            // TODO unit test for the property 'Ar'
        }
        /// <summary>
        /// Test the property 'Bg'
        /// </summary>
        [Test]
        public void BgTest()
        {
            // TODO unit test for the property 'Bg'
        }
        /// <summary>
        /// Test the property 'Fr'
        /// </summary>
        [Test]
        public void FrTest()
        {
            // TODO unit test for the property 'Fr'
        }
        /// <summary>
        /// Test the property 'Sl'
        /// </summary>
        [Test]
        public void SlTest()
        {
            // TODO unit test for the property 'Sl'
        }
        /// <summary>
        /// Test the property 'El'
        /// </summary>
        [Test]
        public void ElTest()
        {
            // TODO unit test for the property 'El'
        }
        /// <summary>
        /// Test the property 'Hr'
        /// </summary>
        [Test]
        public void HrTest()
        {
            // TODO unit test for the property 'Hr'
        }
        /// <summary>
        /// Test the property 'Sr'
        /// </summary>
        [Test]
        public void SrTest()
        {
            // TODO unit test for the property 'Sr'
        }
        /// <summary>
        /// Test the property 'Et'
        /// </summary>
        [Test]
        public void EtTest()
        {
            // TODO unit test for the property 'Et'
        }
        /// <summary>
        /// Test the property 'Sv'
        /// </summary>
        [Test]
        public void SvTest()
        {
            // TODO unit test for the property 'Sv'
        }
        /// <summary>
        /// Test the property 'Th'
        /// </summary>
        [Test]
        public void ThTest()
        {
            // TODO unit test for the property 'Th'
        }
        /// <summary>
        /// Test the property 'Bs'
        /// </summary>
        [Test]
        public void BsTest()
        {
            // TODO unit test for the property 'Bs'
        }
        /// <summary>
        /// Test the property 'Da'
        /// </summary>
        [Test]
        public void DaTest()
        {
            // TODO unit test for the property 'Da'
        }
        /// <summary>
        /// Test the property 'De'
        /// </summary>
        [Test]
        public void DeTest()
        {
            // TODO unit test for the property 'De'
        }
        /// <summary>
        /// Test the property 'Mk'
        /// </summary>
        [Test]
        public void MkTest()
        {
            // TODO unit test for the property 'Mk'
        }
        /// <summary>
        /// Test the property 'No'
        /// </summary>
        [Test]
        public void NoTest()
        {
            // TODO unit test for the property 'No'
        }
        /// <summary>
        /// Test the property 'Ru'
        /// </summary>
        [Test]
        public void RuTest()
        {
            // TODO unit test for the property 'Ru'
        }

    }

}
