/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing FeatureTvshowAttributesSeasons
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeatureTvshowAttributesSeasonsTests
    {
        // TODO uncomment below to declare an instance variable for FeatureTvshowAttributesSeasons
        //private FeatureTvshowAttributesSeasons instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureTvshowAttributesSeasons
            //instance = new FeatureTvshowAttributesSeasons();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureTvshowAttributesSeasons
        /// </summary>
        [Test]
        public void FeatureTvshowAttributesSeasonsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FeatureTvshowAttributesSeasons
            //Assert.IsInstanceOf(typeof(FeatureTvshowAttributesSeasons), instance);
        }


        /// <summary>
        /// Test the property 'SeasonNumber'
        /// </summary>
        [Test]
        public void SeasonNumberTest()
        {
            // TODO unit test for the property 'SeasonNumber'
        }
        /// <summary>
        /// Test the property 'Episodes'
        /// </summary>
        [Test]
        public void EpisodesTest()
        {
            // TODO unit test for the property 'Episodes'
        }

    }

}
