/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2008
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2008Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2008
        //private InlineResponse2008 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2008
            //instance = new InlineResponse2008();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2008
        /// </summary>
        [Test]
        public void InlineResponse2008InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2008
            //Assert.IsInstanceOf(typeof(InlineResponse2008), instance);
        }


        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Test]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }
        /// <summary>
        /// Test the property 'Fname'
        /// </summary>
        [Test]
        public void FnameTest()
        {
            // TODO unit test for the property 'Fname'
        }
        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Test]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }
        /// <summary>
        /// Test the property 'Allowed'
        /// </summary>
        [Test]
        public void AllowedTest()
        {
            // TODO unit test for the property 'Allowed'
        }
        /// <summary>
        /// Test the property 'Remaining'
        /// </summary>
        [Test]
        public void RemainingTest()
        {
            // TODO unit test for the property 'Remaining'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
