/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2006
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2006Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2006
        //private InlineResponse2006 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2006
            //instance = new InlineResponse2006();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2006
        /// </summary>
        [Test]
        public void InlineResponse2006InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2006
            //Assert.IsInstanceOf(typeof(InlineResponse2006), instance);
        }


        /// <summary>
        /// Test the property 'Movie'
        /// </summary>
        [Test]
        public void MovieTest()
        {
            // TODO unit test for the property 'Movie'
        }
        /// <summary>
        /// Test the property 'Episode'
        /// </summary>
        [Test]
        public void EpisodeTest()
        {
            // TODO unit test for the property 'Episode'
        }
        /// <summary>
        /// Test the property 'Tv'
        /// </summary>
        [Test]
        public void TvTest()
        {
            // TODO unit test for the property 'Tv'
        }

    }

}
