/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004Attributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004AttributesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004Attributes
        //private InlineResponse2004Attributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004Attributes
            //instance = new InlineResponse2004Attributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004Attributes
        /// </summary>
        [Test]
        public void InlineResponse2004AttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2004Attributes
            //Assert.IsInstanceOf(typeof(InlineResponse2004Attributes), instance);
        }


        /// <summary>
        /// Test the property 'SubtitleId'
        /// </summary>
        [Test]
        public void SubtitleIdTest()
        {
            // TODO unit test for the property 'SubtitleId'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'DownloadCount'
        /// </summary>
        [Test]
        public void DownloadCountTest()
        {
            // TODO unit test for the property 'DownloadCount'
        }
        /// <summary>
        /// Test the property 'NewDownloadCount'
        /// </summary>
        [Test]
        public void NewDownloadCountTest()
        {
            // TODO unit test for the property 'NewDownloadCount'
        }
        /// <summary>
        /// Test the property 'HearingImpaired'
        /// </summary>
        [Test]
        public void HearingImpairedTest()
        {
            // TODO unit test for the property 'HearingImpaired'
        }
        /// <summary>
        /// Test the property 'Hd'
        /// </summary>
        [Test]
        public void HdTest()
        {
            // TODO unit test for the property 'Hd'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Fps'
        /// </summary>
        [Test]
        public void FpsTest()
        {
            // TODO unit test for the property 'Fps'
        }
        /// <summary>
        /// Test the property 'Votes'
        /// </summary>
        [Test]
        public void VotesTest()
        {
            // TODO unit test for the property 'Votes'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'Ratings'
        /// </summary>
        [Test]
        public void RatingsTest()
        {
            // TODO unit test for the property 'Ratings'
        }
        /// <summary>
        /// Test the property 'FromTrusted'
        /// </summary>
        [Test]
        public void FromTrustedTest()
        {
            // TODO unit test for the property 'FromTrusted'
        }
        /// <summary>
        /// Test the property 'ForeignPartsOnly'
        /// </summary>
        [Test]
        public void ForeignPartsOnlyTest()
        {
            // TODO unit test for the property 'ForeignPartsOnly'
        }
        /// <summary>
        /// Test the property 'AiTranslated'
        /// </summary>
        [Test]
        public void AiTranslatedTest()
        {
            // TODO unit test for the property 'AiTranslated'
        }
        /// <summary>
        /// Test the property 'MachineTranslated'
        /// </summary>
        [Test]
        public void MachineTranslatedTest()
        {
            // TODO unit test for the property 'MachineTranslated'
        }
        /// <summary>
        /// Test the property 'UploadDate'
        /// </summary>
        [Test]
        public void UploadDateTest()
        {
            // TODO unit test for the property 'UploadDate'
        }
        /// <summary>
        /// Test the property 'Release'
        /// </summary>
        [Test]
        public void ReleaseTest()
        {
            // TODO unit test for the property 'Release'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'LegacySubtitleId'
        /// </summary>
        [Test]
        public void LegacySubtitleIdTest()
        {
            // TODO unit test for the property 'LegacySubtitleId'
        }
        /// <summary>
        /// Test the property 'Uploader'
        /// </summary>
        [Test]
        public void UploaderTest()
        {
            // TODO unit test for the property 'Uploader'
        }
        /// <summary>
        /// Test the property 'FeatureDetails'
        /// </summary>
        [Test]
        public void FeatureDetailsTest()
        {
            // TODO unit test for the property 'FeatureDetails'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'RelatedLinks'
        /// </summary>
        [Test]
        public void RelatedLinksTest()
        {
            // TODO unit test for the property 'RelatedLinks'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Test]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

    }

}
