/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004AttributesFeatureDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004AttributesFeatureDetailsTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004AttributesFeatureDetails
        //private InlineResponse2004AttributesFeatureDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004AttributesFeatureDetails
            //instance = new InlineResponse2004AttributesFeatureDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004AttributesFeatureDetails
        /// </summary>
        [Test]
        public void InlineResponse2004AttributesFeatureDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2004AttributesFeatureDetails
            //Assert.IsInstanceOf(typeof(InlineResponse2004AttributesFeatureDetails), instance);
        }


        /// <summary>
        /// Test the property 'FeatureId'
        /// </summary>
        [Test]
        public void FeatureIdTest()
        {
            // TODO unit test for the property 'FeatureId'
        }
        /// <summary>
        /// Test the property 'FeatureType'
        /// </summary>
        [Test]
        public void FeatureTypeTest()
        {
            // TODO unit test for the property 'FeatureType'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'MovieName'
        /// </summary>
        [Test]
        public void MovieNameTest()
        {
            // TODO unit test for the property 'MovieName'
        }
        /// <summary>
        /// Test the property 'ImdbId'
        /// </summary>
        [Test]
        public void ImdbIdTest()
        {
            // TODO unit test for the property 'ImdbId'
        }
        /// <summary>
        /// Test the property 'TmdbId'
        /// </summary>
        [Test]
        public void TmdbIdTest()
        {
            // TODO unit test for the property 'TmdbId'
        }

    }

}
