/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2002Data
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2002DataTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2002Data
        //private InlineResponse2002Data instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2002Data
            //instance = new InlineResponse2002Data();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2002Data
        /// </summary>
        [Test]
        public void InlineResponse2002DataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2002Data
            //Assert.IsInstanceOf(typeof(InlineResponse2002Data), instance);
        }


        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Test]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }
        /// <summary>
        /// Test the property 'LanguageName'
        /// </summary>
        [Test]
        public void LanguageNameTest()
        {
            // TODO unit test for the property 'LanguageName'
        }

    }

}
