/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse200User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse200UserTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200User
        //private InlineResponse200User instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse200User
            //instance = new InlineResponse200User();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse200User
        /// </summary>
        [Test]
        public void InlineResponse200UserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse200User
            //Assert.IsInstanceOf(typeof(InlineResponse200User), instance);
        }


        /// <summary>
        /// Test the property 'AllowedDownloads'
        /// </summary>
        [Test]
        public void AllowedDownloadsTest()
        {
            // TODO unit test for the property 'AllowedDownloads'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'ExtInstalled'
        /// </summary>
        [Test]
        public void ExtInstalledTest()
        {
            // TODO unit test for the property 'ExtInstalled'
        }
        /// <summary>
        /// Test the property 'Vip'
        /// </summary>
        [Test]
        public void VipTest()
        {
            // TODO unit test for the property 'Vip'
        }

    }

}
