/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004AttributesFiles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004AttributesFilesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004AttributesFiles
        //private InlineResponse2004AttributesFiles instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004AttributesFiles
            //instance = new InlineResponse2004AttributesFiles();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004AttributesFiles
        /// </summary>
        [Test]
        public void InlineResponse2004AttributesFilesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineResponse2004AttributesFiles
            //Assert.IsInstanceOf(typeof(InlineResponse2004AttributesFiles), instance);
        }


        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Test]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }
        /// <summary>
        /// Test the property 'CdNumber'
        /// </summary>
        [Test]
        public void CdNumberTest()
        {
            // TODO unit test for the property 'CdNumber'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

    }

}
