/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OpenSubtitles.Api;
using OpenSubtitles.Model;
using OpenSubtitles.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing SubtitleAttributesUploader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubtitleAttributesUploaderTests
    {
        // TODO uncomment below to declare an instance variable for SubtitleAttributesUploader
        //private SubtitleAttributesUploader instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubtitleAttributesUploader
            //instance = new SubtitleAttributesUploader();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubtitleAttributesUploader
        /// </summary>
        [Test]
        public void SubtitleAttributesUploaderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SubtitleAttributesUploader
            //Assert.IsInstanceOf(typeof(SubtitleAttributesUploader), instance);
        }


        /// <summary>
        /// Test the property 'UploaderId'
        /// </summary>
        [Test]
        public void UploaderIdTest()
        {
            // TODO unit test for the property 'UploaderId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }

    }

}
