/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using OpenSubtitles.Client;
using OpenSubtitles.Api;
using OpenSubtitles.Model;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing DiscoverApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DiscoverApiTests
    {
        private DiscoverApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DiscoverApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DiscoverApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' DiscoverApi
            //Assert.IsInstanceOf(typeof(DiscoverApi), instance);
        }

        
        /// <summary>
        /// Test Latest
        /// </summary>
        [Test]
        public void LatestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languages = null;
            //string type = null;
            //var response = instance.Latest(languages, type);
            //Assert.IsInstanceOf(typeof(InlineResponse2004), response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test MostDownloaded
        /// </summary>
        [Test]
        public void MostDownloadedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languages = null;
            //string type = null;
            //var response = instance.MostDownloaded(languages, type);
            //Assert.IsInstanceOf(typeof(InlineResponse2005), response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test Popular
        /// </summary>
        [Test]
        public void PopularTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string languages = null;
            //string type = null;
            //var response = instance.Popular(languages, type);
            //Assert.IsInstanceOf(typeof(Subtitle), response, "response is Subtitle");
        }
        
    }

}
