/*
 * OpenSubtitles API
 *
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using OpenSubtitles.Client;
using OpenSubtitles.Api;
using OpenSubtitles.Model;

namespace OpenSubtitles.Test
{
    /// <summary>
    ///  Class for testing UtilitiesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UtilitiesApiTests
    {
        private UtilitiesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UtilitiesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UtilitiesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UtilitiesApi
            //Assert.IsInstanceOf(typeof(UtilitiesApi), instance);
        }

        
        /// <summary>
        /// Test Guessit
        /// </summary>
        [Test]
        public void GuessitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filename = null;
            //var response = instance.Guessit(filename);
            //Assert.IsInstanceOf(typeof(InlineResponse2009), response, "response is InlineResponse2009");
        }
        
    }

}
